### ISSUE TITLE
didn´t load Folder from mailserver

### ISSUE THREAD

**Issue by Happyfeet01** [owncloud/mail#1512]
### Steps to reproduce
1. connect Emailaccount with local mailserver
2. open mail

### Actual behaviour
the emailfolders won´t sync with this mailclient. No Send, No Draft or other folder

### ownCloud Mail

**ownCloud Mail version:** (see ownCloud apps admin page)

**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)
selfhosted, imap/smtp.cloud-surfer.de
**Transport security - IMAP:** (None, SSL, TLS, STARTTLS) 
SSL
**Transport security - SMTP:** (None, SSL, TLS, STARTTLS)
SSL
**Number of accounts:**
1
**ownCloud Mail version build date:** (only if you are using a Nightly Build)

0.5.1
### ownCloud Core
9.0.1
#### Server configuration
**Operating system**:
ubuntu 14.04 LTS
**Web server:**
Apache2
**Database:**
MySQL
**PHP version:**
PHP7
**ownCloud version:** (see ownCloud admin page)
owncloud 9.0.1
**Updated from an older ownCloud or fresh install:**
updated
**List of activated apps:**

```
Enabled:                                                                             
  - activity: 2.2.1                                                                  
  - calendar: 1.2.2                                                                  
  - comments: 0.2                                                                    
  - contacts: 1.3.1.0                                                                
  - dav: 0.1.6                                                                       
  - documents: true                                                                  
  - encryption: 1.2.0                                                                
  - federatedfilesharing: 0.1.0                                                      
  - federation: 0.0.4                                                                
  - files: 1.4.4                                                                     
  - files_external: 0.5.2                                                            
  - files_mv: true                                                                   
  - files_sharing: 0.9.1                                                             
  - files_texteditor: 2.1                                                            
  - files_trashbin: 0.8.0                                                            
  - files_versions: 1.2.0                                                            
  - files_videoplayer: 0.9.8                                                         
  - firstrunwizard: 1.1                                                              
  - gallery: 14.5.0                                                                  
  - libreonline: true                                                                
  - mail: 0.5.1                                                                      
  - music: true                                                                      
  - news: 8.8.0                                                                      
  - notes: true                                                                      
  - notifications: 0.2.3                                                             
  - ocdownloader: 1.5                                                                
  - provisioning_api: 0.4.1                                                          
  - sketch: true                                                                     
  - systemtags: 0.2                                                                  
  - tasks: true                                                                      
  - templateeditor: 0.1                                                              
  - updatenotification: 0.1.0                                                        
Disabled:                                                                            
  - external                                                                         
  - files_pdfviewer                                                                  
  - user_external                                                                    
  - user_ldap  
```

**The content of config/config.php:**

```
{                                                                                                            
    "system": {                                                                                              
        "instanceid": "ocpsovzwa7ww",                                                                        
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",                                                     
        "secret": "***REMOVED SENSITIVE VALUE***",                                                           
        "trusted_domains": [                                                                                 
            "cloud-surfer.eu",                                                                               
            "cloud.cloud-surfer.eu"                                                                          
        ],                                                                                                   
        "datadirectory": "\/mnt\/owncloud\/data",                                                            
        "overwrite.cli.url": "http:\/\/81.169.130.87\/",                                                     
        "dbtype": "mysql",                                                                                   
        "version": "9.0.2.2",                                                                                
        "dbname": "owncloud",                                                                                
        "dbhost": "localhost",                                                                               
        "dbtableprefix": "oc_",                                                                              
        "dbuser": "***REMOVED SENSITIVE VALUE***",                                                           
        "dbpassword": "***REMOVED SENSITIVE VALUE***",                                                       
        "logtimezone": "Europe\/Berlin",                                                                     
        "installed": true,                                                                                   
        "loglevel": 3,                                                                                       
        "maintenance": false,                                                                                
        "appstore.experimental.enabled": true,                                                               
        "singleuser": false,                                                                                 
        "mail_smtpmode": "php",                                                                              
        "mail_from_address": "mail",                                                                         
        "mail_domain": "cloud-surfer.eu",                                                                    
        "mail_smtpauthtype": "PLAIN",                                                                        
        "mail_smtpauth": 1,                                                                                  
        "mail_smtphost": "mail.cloud-surfer.eu",                                                             
        "mail_smtpport": "587",                                                                              
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",                                                    
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",                                                
        "mail_smtpsecure": "ssl",                                                                            
        "updatechecker": true,                                                                               
        "theme": "mytheme",                                                                                  
        "memcache.local": "\\OC\\Memcache\\Redis",                                                           
        "memcache.locking": "\\OC\\Memcache\\Redis",                                                         
        "redis": {                                                                                           
            "host": "localhost",                                                                             
            "port": 6379                                                                                     
        },                                                                                                   
        "updater.secret": "***REMOVED SENSITIVE VALUE***"                                                    
    }                                                                                                        
}
```

#### Client configuration
**Browser:**
Chrome
**Operating system:**
Windows7/10
##### Web server error log
```

```

##### ownCloud log (data/owncloud.log)
```
Error	PHP	Undefined index: id at /var/www/vhosts/cloud-surfer.eu/httpdocs/owncloud/apps/mail/lib/service/contactsintegration.php#55
```

##### Horde IMAP log (data/horde_imap.log)
```
not possible ATM, Error 500 when enable debug-mode
```

##### Horde SMTP log (data/horde_smtp.log)
```
not possible ATM, Error 500 when enable debug-mode
```
